
name: Build & Deploy
on:
  push:
    branches:
      - main

env:
  SKIP_PREFLIGHT_CHECK: true
  TZ: Asia/Shanghai

jobs:
  build-deploy:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 20

    - run: yarn install
    - run: yarn run build:all
    - run: yarn build:docs
    - run: yarn build:example

    - name: Create ZIP
      run: |
          cd ./examples/template/ 
          zip -r template.zip . -x "node_modules/*" "dist/*" "src/.fairys/*" ".DS_Store"
          mv template.zip ../../docs/doc_build/
          ls ../../docs/doc_build/

    - name: Create Doc
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs/doc_build

    - name: Create Tag
      id: create_tag
      uses: jaywcjlove/create-tag-action@main
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        package-path: ./packages/ui/package.json

    - name: Generate changelog
      id: changelog
      uses: jaywcjlove/changelog-generator@main
      if: steps.create_tag.outputs.successful == 'true'
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        head-ref: ${{ steps.create_tag.outputs.version }}
        filter-author: (SunLxy|dependabot[bot]|Renovate Bot)
        filter: '[R|r]elease[d]\s+[v|V]\d(\.\d+){0,2}'

    - name: Create Release
      uses: ncipollo/release-action@v1
      if: steps.create_tag.outputs.successful == 'true'
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        name: ${{ steps.create_tag.outputs.version }}
        tag: ${{ steps.create_tag.outputs.version }}
        body: |
          ```bash
          npm i @fairys/admin-tools-react@${{ steps.create_tag.outputs.version }}
          npm i @fairys/admin-tools-react-plugins@${{ steps.create_tag.outputs.version }}
          ```
          ${{ steps.changelog.outputs.compareurl }}
          ${{ steps.changelog.outputs.changelog }}

    - name: Publish 🚀
      uses: SunLxy/npm-publish@main
      with:
        token: ${{ secrets.NPM_TOKEN }}
        workspaces: |
          core
          packages/*

  